title: Niruthi Selva
logo: /assets/img/headshot_circle.png
description: [Resume](https://drive.google.com/file/d/1hIzHDCypJusBvmkAMY3Vezat7hzwYe72/view?usp=sharing) | LinkedIn | GitHub
theme: jekyll-theme-minimal
