title: Niruthi Selva
logo: /assets/img/headshot_circle.png
description:
  <p align="center">
  <a href="https://drive.google.com/file/d/12V8qU46yNrvxOoWrpdwSTwoTnxNQgtN2/view?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/niruthi-selva/">LinkedIn</a> |
  <a href="https://www.github.com/Niruthiha">GitHub</a> |
  <a href="https://www.medium.com/@niruthiha2000">Medium Blogs</a>
  </p>
  
theme: jekyll-theme-minimal

