title: Niruthi Selva
logo: /assets/img/headshot_circle.png
description:
  <p align="center">
  <a href="https://drive.google.com/file/d/1hIzHDCypJusBvmkAMY3Vezat7hzwYe72/view?usp=drive_link">Resume</a> |
  <a href="https://www.linkedin.com/in/niruthi-selva/">LinkedIn</a> |
  <a href="hhttps://github.com/Niruthiha">GitHub</a>
  </p>
  
theme: jekyll-theme-minimal

